In [90]:
import pandas as pd
import numpy as np 

In [91]:
data = pd.read_csv("Reviews.csv")

In [92]:
print(data)

                      Review  Label
0          I loved the movie      1
1          I hated the movie      0
2   a great movie good movie      1
3                poor acting      0
4  great acting a good movie      1


In [93]:
data.head(2)

Review  Label
0  I loved the movie      1
1  I hated the movie      0

In [94]:
data.columns

Index(['Review', 'Label'], dtype='object')

In [95]:
data.shape

(5, 2)

In [96]:
data.dtypes

Review    object
Label      int64
dtype: object

In [97]:
data.nunique()

Review    5
Label     2
dtype: int64

In [98]:
review = data['Review']
label = data['Label']

In [99]:
print(review)

0            I loved the movie
1            I hated the movie
2     a great movie good movie
3                  poor acting
4    great acting a good movie
Name: Review, dtype: object


In [100]:
print(label)

0    1
1    0
2    1
3    0
4    1
Name: Label, dtype: int64


In [101]:
unique_word = []
for x in review:
    for y in x.split(' ') :
        if y not in unique_word:
            unique_word.append(y)

In [102]:
print(unique_word)

['I', 'loved', 'the', 'movie', 'hated', 'a', 'great', 'good', 'poor', 'acting']


In [103]:
count = np.zeros((len(review), len(unique_word)))
print(count)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [104]:
occur=0
elem=[]
for a in range(len(review)):
    for y in unique_word:
        #print(y)
        for x in review[a].split(' '):
            #print(x)
            if y==x:
                #col = col+1
                occur +=1
                #print(occur,x,y)
            #insert in count
        elem.append(occur)    
        print(y,occur)
        #count[][]=occur
        occur = 0
            

I 1
loved 1
the 1
movie 1
hated 0
a 0
great 0
good 0
poor 0
acting 0
I 1
loved 0
the 1
movie 1
hated 1
a 0
great 0
good 0
poor 0
acting 0
I 0
loved 0
the 0
movie 2
hated 0
a 1
great 1
good 1
poor 0
acting 0
I 0
loved 0
the 0
movie 0
hated 0
a 0
great 0
good 0
poor 1
acting 1
I 0
loved 0
the 0
movie 1
hated 0
a 1
great 1
good 1
poor 0
acting 1


In [105]:
a=0
for y in range(len(review)):
    
    for x in range(len(elem)):
        if (x>len(unique_word)-1):
            break
        count[y][x] = elem[a]
        a = a + 1

In [106]:
for x in unique_word:
    print(x, end = '\t')   
print('\n',"-"*80,sep = '')    
for x in range(len(review)):
    for y in range(len(unique_word)):
        print(int(count[x][y]) , end ='\t')
    print() 

I	loved	the	movie	hated	a	great	good	poor	acting	
--------------------------------------------------------------------------------
1	1	1	1	0	0	0	0	0	0	
1	0	1	1	1	0	0	0	0	0	
0	0	0	2	0	1	1	1	0	0	
0	0	0	0	0	0	0	0	1	1	
0	0	0	1	0	1	1	1	0	1	


In [107]:
sum_row = []
su=0
for y in range(len(review)):
    for x in range(len(unique_word)):
        su+=int(count[y][x])
    sum_row.append(su)
    su=0
print(sum_row)    

[4, 4, 5, 2, 5]


In [108]:
p_s =0
n_s =0
for x in label:
    if x==1:
        p_s +=1
    if x==0:
        n_s +=1
pos_p = p_s/(p_s+n_s)
neg_p = n_s/(p_s+n_s)
print(pos_p ,'||', neg_p)

0.6 || 0.4


In [109]:
pos_list = []
neg_list = []
psum=0
nsum=0
for x in range(len(unique_word)):
    #print(unique_word[x])
    for y in range(len(review)):
        if(label[y]==1):
            psum+=count[y][x]
    pos_list.append(int(psum))        
    #print(int(psum))
    psum=0
            
for x in range(len(unique_word)):
    #print(unique_word[x])
    for y in range(len(review)):
        if(label[y]==0):
            nsum+=count[y][x]
    neg_list.append(int(nsum))        
    #print(int(nsum))
    nsum=0            

In [110]:
print(pos_list)
sum_pos=0
for x in range(len(pos_list)):
    sum_pos += pos_list[x]
print(sum_pos)    

[1, 1, 1, 4, 0, 2, 2, 2, 0, 1]
14


In [111]:
print(neg_list)
sum_neg=0
for x in range(len(neg_list)):
    sum_neg += neg_list[x]
print(sum_neg)    

[1, 0, 1, 1, 1, 0, 0, 0, 1, 1]
6


In [112]:
pword_p = []
for x in range(len(unique_word)):
    ans = (pos_list[x]+1)/(sum_pos+len(unique_word))
    pword_p.append(ans)
    print(unique_word[x],'\t',ans)

I 	 0.08333333333333333
loved 	 0.08333333333333333
the 	 0.08333333333333333
movie 	 0.20833333333333334
hated 	 0.041666666666666664
a 	 0.125
great 	 0.125
good 	 0.125
poor 	 0.041666666666666664
acting 	 0.08333333333333333


In [113]:
nword_p = []
for x in range(len(unique_word)):
    ans = (neg_list[x]+1)/(sum_neg+len(unique_word))
    nword_p.append(ans)
    print(unique_word[x],'\t',ans)

I 	 0.125
loved 	 0.0625
the 	 0.125
movie 	 0.125
hated 	 0.125
a 	 0.0625
great 	 0.0625
good 	 0.0625
poor 	 0.125
acting 	 0.125


In [114]:
tar_arr = (target.split(' '))
print(tar_arr)

['I', 'loved', 'the', 'movie']


In [115]:
for x in unique_word:
    print(x , end = ',')

I,loved,the,movie,hated,a,great,good,poor,acting,

In [117]:
target = input(("Enter your statement: "))
out_pos = pos_p
out_neg = neg_p
for x in range(len(tar_arr)):
    
    for y in range(len(unique_word)):
        
        if (tar_arr[x])==(unique_word[y]):
            
            out_pos *=  pword_p[y]
            out_neg *=  nword_p[y]
            break
print(out_pos)
print(out_neg)
if out_pos>out_neg:
    print('Positive Sentiment')
else:
    print('Negative Sentiment')

Enter your statement: good movie
7.233796296296295e-05
4.8828125e-05
Positive Sentiment
